# Generated by Django 5.2.4 on 2025-12-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
