# Generated by Django 5.2.4 on 2025-12-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='about_image'),
        ),
    ]
