# Generated by Django 5.2.4 on 2025-12-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_about_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='model_description',
            new_name='about_description',
        ),
    ]
