# Generated by Django 5.2.4 on 2025-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='defaults/ilmnote_default_image.jpg', upload_to='uploads/%y/%m/%d'),
        ),
    ]
